apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: td-hello
  name: td-hello
spec:
  containers:
  - image: go-terry-hello
    imagePullPolicy: IfNotPresent
    name: td-hello
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
