apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: microk8s-homelab
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
    kubelet:
      tlsVerify: false
  features:
    orchestratorExplorer:
      enabled: true
    apm:
      enabled: false
    logCollection:
      enabled: true
      containerCollectAll: true
  override:
    nodeAgent:
#      env:
#        - name: DD_IGNORE_AUTOCONF
#          value: kube_scheduler kube_controller_manager etcd
    clusterAgent:
      env:
        - name: DD_CLUSTER_NAME
          value: microk8s-homelab
